
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author migyu
 */
public class MainFrame extends javax.swing.JFrame {
    String screenTemp = ""; // 현재 화면에 보이는 문자
    String strResult = "";
    String strOperator = "";
    double tempNum = 0;   // 화면에 보이는 문자를 실수로 변환한 것
    double calResult = 0; // 연산 결과
    private String strMemory = "";
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("공학용 계산기");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        rbtnHex = new javax.swing.JRadioButton();
        rbtnDec = new javax.swing.JRadioButton();
        rbtnOct = new javax.swing.JRadioButton();
        rbtnBin = new javax.swing.JRadioButton();
        btnCE = new javax.swing.JButton();
        resultField = new javax.swing.JTextField();
        btnC = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        btnSta = new javax.swing.JButton();
        btnPM = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        btnNot = new javax.swing.JButton();
        btnLsh = new javax.swing.JButton();
        btnXor = new javax.swing.JButton();
        btnOr = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnAnd = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnComma = new javax.swing.JButton();
        Sta30 = new javax.swing.JButton();
        Sta31 = new javax.swing.JButton();
        Sta32 = new javax.swing.JButton();
        BtnOne = new javax.swing.JButton();
        BtnThree = new javax.swing.JButton();
        BtnTwo = new javax.swing.JButton();
        btnX3 = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        Sta42 = new javax.swing.JButton();
        btnDms = new javax.swing.JButton();
        btnFE = new javax.swing.JButton();
        Sta45 = new javax.swing.JButton();
        Sta46 = new javax.swing.JButton();
        btnFacto = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btn1x = new javax.swing.JButton();
        btnX2 = new javax.swing.JButton();
        btnMP = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        btnMS = new javax.swing.JButton();
        btnMC = new javax.swing.JButton();
        btnMR = new javax.swing.JButton();
        Sta56 = new javax.swing.JButton();
        Sta57 = new javax.swing.JButton();
        Sta58 = new javax.swing.JButton();
        Sta59 = new javax.swing.JButton();
        btnInt = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(227, 221, 211));

        buttonGroup2.add(rbtnHex);
        rbtnHex.setText("Hex");
        rbtnHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnHexActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtnDec);
        rbtnDec.setText("Dec");
        rbtnDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDecActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtnOct);
        rbtnOct.setText("Oct");
        rbtnOct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOctActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtnBin);
        rbtnBin.setText("Bin");
        rbtnBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnBinActionPerformed(evt);
            }
        });

        btnCE.setBackground(new java.awt.Color(235, 233, 230));
        btnCE.setForeground(new java.awt.Color(255, 0, 51));
        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        resultField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultField.setText("0");
        resultField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultFieldActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(235, 233, 230));
        btnC.setForeground(new java.awt.Color(255, 0, 51));
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnBackspace.setBackground(new java.awt.Color(235, 233, 230));
        btnBackspace.setForeground(new java.awt.Color(255, 0, 51));
        btnBackspace.setText("Backspace");
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackspaceActionPerformed(evt);
            }
        });

        jRadioButton5.setText("Degrees");

        jRadioButton6.setText("Grads");

        jRadioButton7.setText("Radians");

        btnSta.setBackground(new java.awt.Color(235, 233, 230));
        btnSta.setText("Sta");
        btnSta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaActionPerformed(evt);
            }
        });

        btnPM.setBackground(new java.awt.Color(235, 233, 230));
        btnPM.setForeground(new java.awt.Color(51, 51, 255));
        btnPM.setText("+/-");
        btnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(235, 233, 230));
        btn0.setForeground(new java.awt.Color(51, 51, 255));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(235, 233, 230));
        btn1.setForeground(new java.awt.Color(51, 51, 255));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(235, 233, 230));
        btn3.setForeground(new java.awt.Color(51, 51, 255));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(235, 233, 230));
        btn2.setForeground(new java.awt.Color(51, 51, 255));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(235, 233, 230));
        btn6.setForeground(new java.awt.Color(51, 51, 255));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(235, 233, 230));
        btn5.setForeground(new java.awt.Color(51, 51, 255));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(235, 233, 230));
        btn4.setForeground(new java.awt.Color(51, 51, 255));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(235, 233, 230));
        btn7.setForeground(new java.awt.Color(51, 51, 255));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(235, 233, 230));
        btn9.setForeground(new java.awt.Color(51, 51, 255));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(235, 233, 230));
        btn8.setForeground(new java.awt.Color(51, 51, 255));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btnPlus.setBackground(new java.awt.Color(235, 233, 230));
        btnPlus.setForeground(new java.awt.Color(255, 0, 0));
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(235, 233, 230));
        btnMin.setForeground(new java.awt.Color(255, 0, 0));
        btnMin.setText("-");
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });

        btnNot.setBackground(new java.awt.Color(235, 233, 230));
        btnNot.setForeground(new java.awt.Color(255, 0, 0));
        btnNot.setText("Not");
        btnNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotActionPerformed(evt);
            }
        });

        btnLsh.setBackground(new java.awt.Color(235, 233, 230));
        btnLsh.setForeground(new java.awt.Color(255, 0, 0));
        btnLsh.setText("Lsh");
        btnLsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLshActionPerformed(evt);
            }
        });

        btnXor.setBackground(new java.awt.Color(235, 233, 230));
        btnXor.setForeground(new java.awt.Color(255, 0, 0));
        btnXor.setText("Xor");
        btnXor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXorActionPerformed(evt);
            }
        });

        btnOr.setBackground(new java.awt.Color(235, 233, 230));
        btnOr.setForeground(new java.awt.Color(255, 0, 0));
        btnOr.setText("Or");
        btnOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrActionPerformed(evt);
            }
        });

        btnMul.setBackground(new java.awt.Color(235, 233, 230));
        btnMul.setForeground(new java.awt.Color(255, 0, 0));
        btnMul.setText("*");
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });

        btnDiv.setBackground(new java.awt.Color(235, 233, 230));
        btnDiv.setForeground(new java.awt.Color(255, 0, 0));
        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnAnd.setBackground(new java.awt.Color(235, 233, 230));
        btnAnd.setForeground(new java.awt.Color(255, 0, 0));
        btnAnd.setText("And");
        btnAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndActionPerformed(evt);
            }
        });

        btnMod.setBackground(new java.awt.Color(235, 233, 230));
        btnMod.setForeground(new java.awt.Color(255, 0, 0));
        btnMod.setText("Mod");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnComma.setBackground(new java.awt.Color(235, 233, 230));
        btnComma.setForeground(new java.awt.Color(51, 51, 255));
        btnComma.setText(".");
        btnComma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommaActionPerformed(evt);
            }
        });

        Sta30.setForeground(new java.awt.Color(153, 153, 153));
        Sta30.setText("D");
        Sta30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta30ActionPerformed(evt);
            }
        });

        Sta31.setForeground(new java.awt.Color(153, 153, 153));
        Sta31.setText("F");
        Sta31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta31ActionPerformed(evt);
            }
        });

        Sta32.setForeground(new java.awt.Color(153, 153, 153));
        Sta32.setText("E");
        Sta32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta32ActionPerformed(evt);
            }
        });

        BtnOne.setForeground(new java.awt.Color(153, 153, 153));
        BtnOne.setText("A");
        BtnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOneActionPerformed(evt);
            }
        });

        BtnThree.setForeground(new java.awt.Color(153, 153, 153));
        BtnThree.setText("C");
        BtnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThreeActionPerformed(evt);
            }
        });

        BtnTwo.setForeground(new java.awt.Color(153, 153, 153));
        BtnTwo.setText("B");
        BtnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTwoActionPerformed(evt);
            }
        });

        btnX3.setBackground(new java.awt.Color(235, 233, 230));
        btnX3.setForeground(new java.awt.Color(255, 51, 255));
        btnX3.setText("x^3");
        btnX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX3ActionPerformed(evt);
            }
        });

        btnCos.setBackground(new java.awt.Color(235, 233, 230));
        btnCos.setForeground(new java.awt.Color(255, 51, 255));
        btnCos.setText("cos");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });

        btnSin.setBackground(new java.awt.Color(235, 233, 230));
        btnSin.setForeground(new java.awt.Color(255, 51, 255));
        btnSin.setText("sin");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });

        btnLog.setBackground(new java.awt.Color(235, 233, 230));
        btnLog.setForeground(new java.awt.Color(255, 51, 255));
        btnLog.setText("log");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        btnX.setBackground(new java.awt.Color(235, 233, 230));
        btnX.setForeground(new java.awt.Color(255, 51, 255));
        btnX.setText("x^y");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        btnIn.setBackground(new java.awt.Color(235, 233, 230));
        btnIn.setForeground(new java.awt.Color(255, 51, 255));
        btnIn.setText("In");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        Sta42.setBackground(new java.awt.Color(235, 233, 230));
        Sta42.setForeground(new java.awt.Color(255, 51, 255));
        Sta42.setText("Exp");
        Sta42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta42ActionPerformed(evt);
            }
        });

        btnDms.setBackground(new java.awt.Color(235, 233, 230));
        btnDms.setForeground(new java.awt.Color(255, 51, 255));
        btnDms.setText("dms");
        btnDms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDmsActionPerformed(evt);
            }
        });

        btnFE.setBackground(new java.awt.Color(235, 233, 230));
        btnFE.setForeground(new java.awt.Color(255, 51, 255));
        btnFE.setText("F-E");
        btnFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFEActionPerformed(evt);
            }
        });

        Sta45.setBackground(new java.awt.Color(235, 233, 230));
        Sta45.setForeground(new java.awt.Color(255, 51, 255));
        Sta45.setText(")");
        Sta45.setToolTipText("");
        Sta45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta45ActionPerformed(evt);
            }
        });

        Sta46.setBackground(new java.awt.Color(235, 233, 230));
        Sta46.setForeground(new java.awt.Color(255, 51, 255));
        Sta46.setText("(");
        Sta46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta46ActionPerformed(evt);
            }
        });

        btnFacto.setBackground(new java.awt.Color(235, 233, 230));
        btnFacto.setForeground(new java.awt.Color(255, 51, 255));
        btnFacto.setText("n!");
        btnFacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactoActionPerformed(evt);
            }
        });

        btnTan.setBackground(new java.awt.Color(235, 233, 230));
        btnTan.setForeground(new java.awt.Color(255, 51, 255));
        btnTan.setText("tan");
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });

        btn1x.setBackground(new java.awt.Color(235, 233, 230));
        btn1x.setForeground(new java.awt.Color(255, 51, 255));
        btn1x.setText("1/x");
        btn1x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1xActionPerformed(evt);
            }
        });

        btnX2.setBackground(new java.awt.Color(235, 233, 230));
        btnX2.setForeground(new java.awt.Color(255, 51, 255));
        btnX2.setText("x^2");
        btnX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2ActionPerformed(evt);
            }
        });

        btnMP.setBackground(new java.awt.Color(235, 233, 230));
        btnMP.setForeground(new java.awt.Color(255, 0, 0));
        btnMP.setText("M+");
        btnMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMPActionPerformed(evt);
            }
        });

        btnPi.setBackground(new java.awt.Color(235, 233, 230));
        btnPi.setForeground(new java.awt.Color(0, 51, 255));
        btnPi.setText("pi");
        btnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiActionPerformed(evt);
            }
        });

        btnMS.setBackground(new java.awt.Color(235, 233, 230));
        btnMS.setForeground(new java.awt.Color(255, 0, 0));
        btnMS.setText("MS");
        btnMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMSActionPerformed(evt);
            }
        });

        btnMC.setBackground(new java.awt.Color(235, 233, 230));
        btnMC.setForeground(new java.awt.Color(255, 0, 0));
        btnMC.setText("MC");
        btnMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCActionPerformed(evt);
            }
        });

        btnMR.setBackground(new java.awt.Color(235, 233, 230));
        btnMR.setForeground(new java.awt.Color(255, 0, 0));
        btnMR.setText("MR");
        btnMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRActionPerformed(evt);
            }
        });

        Sta56.setForeground(new java.awt.Color(153, 153, 153));
        Sta56.setText("Dat");
        Sta56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta56ActionPerformed(evt);
            }
        });

        Sta57.setForeground(new java.awt.Color(153, 153, 153));
        Sta57.setText("s");
        Sta57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta57ActionPerformed(evt);
            }
        });

        Sta58.setForeground(new java.awt.Color(153, 153, 153));
        Sta58.setText("Sum");
        Sta58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta58ActionPerformed(evt);
            }
        });

        Sta59.setForeground(new java.awt.Color(153, 153, 153));
        Sta59.setText("Ave");
        Sta59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta59ActionPerformed(evt);
            }
        });

        btnInt.setBackground(new java.awt.Color(235, 233, 230));
        btnInt.setForeground(new java.awt.Color(255, 0, 0));
        btnInt.setText("Int");
        btnInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntActionPerformed(evt);
            }
        });

        btnResult.setBackground(new java.awt.Color(235, 233, 230));
        btnResult.setForeground(new java.awt.Color(255, 0, 0));
        btnResult.setText("=");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Inv");

        jCheckBox2.setText("Hyp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sta56, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Sta59, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sta57, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sta58, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(btn1x, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDms, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnFE, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Sta46, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(Sta45, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Sta42, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnX3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(btnFacto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMS, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMP, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnHex, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnDec, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnOct, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnBin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BtnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(BtnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(BtnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(Sta30, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(Sta32, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(Sta31, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnComma, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnOr, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnXor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnAnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnLsh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(btnNot, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(btnInt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnHex)
                                    .addComponent(rbtnBin)
                                    .addComponent(rbtnOct)
                                    .addComponent(rbtnDec))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton7)
                                    .addComponent(jRadioButton6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sta59, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sta58, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sta57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Sta56, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnAnd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnOr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnXor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnNot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnLsh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnComma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnInt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BtnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BtnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BtnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Sta31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sta32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sta30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Sta45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sta46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDms, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sta42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnX3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFacto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn1x, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        // Clear Entry : 바로 직전 입력한 값만 지움
        screenTemp="";
        
        resultField.setText(screenTemp);
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // Clear : 모두 지움
        calResult = 0;
        tempNum = 0;
        strResult = "";
        screenTemp = "";
        strOperator = "";
        
        resultField.setText("0");
    }//GEN-LAST:event_btnCActionPerformed

    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackspaceActionPerformed
        
        int delIndex = screenTemp.length()-1;
        screenTemp = screenTemp.substring(0 ,delIndex);
        resultField.setText(screenTemp);
    }//GEN-LAST:event_btnBackspaceActionPerformed

    private void btnStaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaActionPerformed
      
    }//GEN-LAST:event_btnStaActionPerformed

    private void btnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMActionPerformed
       
    }//GEN-LAST:event_btnPMActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        screenTemp += 0; resultField.setText(screenTemp);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        screenTemp += 1; resultField.setText(screenTemp);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        screenTemp += 3; resultField.setText(screenTemp);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        screenTemp += 2; resultField.setText(screenTemp);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        screenTemp += 6; resultField.setText(screenTemp);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        screenTemp += 5; resultField.setText(screenTemp);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        screenTemp += 4; resultField.setText(screenTemp);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        screenTemp += 7; resultField.setText(screenTemp);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        screenTemp += 9; resultField.setText(screenTemp);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        screenTemp += 8; resultField.setText(screenTemp);

    }//GEN-LAST:event_btn8ActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        
        tempNum = Double.valueOf(screenTemp); // 화면에 보이는 값을 실수형으로 변환
        
        // * 연산기호를 두 번 누르는 걸 방지할 코드 필요 
        
        // 결과가 초기값(0)이면 계산한 적이 없는 것, 
        // 결과에 스크린에 있는 값을 실수로 형변환한 tempNum 입력
        if(calResult == 0){
            calResult = tempNum;
        } else {
            calResult += tempNum;
        }
            
        strResult = String.valueOf(calResult);
        resultField.setText(strResult);
            
        tempNum = 0;
        screenTemp = "";
        strOperator = "+";                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        
        tempNum = Double.valueOf(screenTemp); // 눌린 값을 실수형으로 변환
        
        // * 연산기호를 두 번 누르는 걸 방지할 코드 필요 
        
        // 결과가 초기값(0)이면 계산한 적이 없는 것,
        // 결과에 스크린에 있는 값을 실수로 형변환한 tempNum 입력
        if(calResult == 0){
            calResult = tempNum;
        } else {
            calResult -= tempNum;
        }
            
        strResult = String.valueOf(calResult);
        resultField.setText(strResult);
            
        tempNum = 0;
        screenTemp = "";
        strOperator = "-";    
    }//GEN-LAST:event_btnMinActionPerformed

    private void btnNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotActionPerformed
        
        screenTemp = resultField.getText();
        calResult = Double.parseDouble(screenTemp);
        if(calResult!=0) calResult= ~(int)calResult;
        resultField.setText(Double.toString(calResult));
    }//GEN-LAST:event_btnNotActionPerformed

    private void btnLshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLshActionPerformed
        tempNum = Double.valueOf(screenTemp);
        
        if(calResult == 0) 
            calResult = tempNum;
        else
            calResult = (int)tempNum << (int)calResult;
        
        strResult = String.valueOf(calResult);
        resultField.setText(strResult);
        
        tempNum = 0;
        screenTemp = "";
        strOperator = "<";
    }//GEN-LAST:event_btnLshActionPerformed

    private void btnXorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXorActionPerformed
        tempNum = Double.valueOf(screenTemp);
        
        if(calResult == 0)
            calResult = tempNum;
        else 
            calResult = (int)tempNum ^ (int) calResult;
        
        strResult = String.valueOf(calResult);
        
        tempNum = 0;
        screenTemp = "";
        strOperator = "^";
    }//GEN-LAST:event_btnXorActionPerformed

    private void btnOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrActionPerformed
        tempNum = Double.valueOf(screenTemp);
        
        if(calResult == 0)
            calResult = tempNum;
        else 
            calResult = (int)tempNum | (int) calResult;
        
        strResult = String.valueOf(calResult);
        
        tempNum = 0;
        screenTemp = "";
        strOperator = "|";
    }//GEN-LAST:event_btnOrActionPerformed

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        
        tempNum = Double.valueOf(screenTemp); // 눌린 값을 실수형으로 변환
        
        // * 연산기호를 두 번 누르는 걸 방지할 코드 필요 
        
        // 결과가 초기값(0)이면 계산한 적이 없는 것,
        // 결과에 스크린에 있는 값을 실수로 형변환한 tempNum 입력
        if(calResult == 0){
            calResult = tempNum;
        } else {
            calResult *= tempNum;
        }    
        strResult = String.valueOf(calResult);
        resultField.setText(strResult);
            
        tempNum = 0;
        screenTemp = "";
        strOperator = "*";    
    }//GEN-LAST:event_btnMulActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        
        tempNum = Double.valueOf(screenTemp); // 눌린 값을 실수형으로 변환
        
        // 결과가 초기값(0)이면 계산한 적이 없는 것,
        // 결과에 스크린에 있는 값을 실수로 형변환한 tempNum 입력
        if(calResult == 0){
            calResult = tempNum;
        } else {
            calResult /= tempNum;
        }     
        strResult = String.valueOf(calResult);
        resultField.setText(strResult);
            
        tempNum = 0;
        screenTemp = "";
        strOperator = "/";     
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnAndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndActionPerformed
        // TODO add your handling code here:
        tempNum = Double.valueOf(screenTemp);
        
        // * 연산기호를 두 번 누르는 걸 방지할 코드 필요 
        
        // 결과가 초기값(0)이면 계산한 적이 없는 것,
        // 결과에 스크린에 있는 값을 실수로 형변환한 tempNum 입력
        if(calResult == 0){
            calResult = tempNum;
        } else {
        // 결과가 초기값이 아니면 계산 수행
            calResult = (int)tempNum & (int)tempNum;
            
            // 문자로 변환 후 화면에 출력
            strResult = String.valueOf(calResult);
            resultField.setText(strResult);
            
            
            tempNum = 0; // 현재숫자 초기화
            strResult = ""; // 화면에 띄워주는 결과값 초기화
            strOperator = "&"; // 연산자는 +
        }
        
    }//GEN-LAST:event_btnAndActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        tempNum = Double.valueOf(screenTemp);
        
        if(calResult == 0)
            calResult = tempNum;
        else
            calResult %= tempNum;
        
        strResult = String.valueOf(calResult);
        
        resultField.setText(strResult);
        
        tempNum = 0;
        screenTemp = "";
        strOperator = "%";
    }//GEN-LAST:event_btnModActionPerformed

    private void btnCommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommaActionPerformed
        
        screenTemp += ".";
        resultField.setText(screenTemp);
    }//GEN-LAST:event_btnCommaActionPerformed

    private void Sta30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta30ActionPerformed

    private void Sta31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta31ActionPerformed

    private void Sta32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta32ActionPerformed

    private void BtnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOneActionPerformed

    private void BtnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnThreeActionPerformed

    private void BtnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTwoActionPerformed

    private void btnX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX3ActionPerformed
        
        screenTemp = resultField.getText();
        calResult = Double.parseDouble(screenTemp);
        if(calResult!= 0)  calResult = Math.pow(calResult, 3);
        resultField.setText(Double.toString(calResult));
    }//GEN-LAST:event_btnX3ActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        calResult = Double.parseDouble(screenTemp);
        if(calResult!=0){
            calResult = Math.cos(Math.toRadians(calResult));
            resultField.setText(Double.toString(calResult));
        }
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        
        calResult = Double.parseDouble(screenTemp);
        if(calResult!=0){
            calResult = Math.sin(Math.toRadians(calResult));
            resultField.setText(Double.toString(calResult));
        }
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        
        screenTemp = resultField.getText();
        calResult = Double.parseDouble(screenTemp);
        if(calResult!=0) {
            calResult = Math.log10(calResult);
            resultField.setText(Double.toString(calResult));
        }
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        
        screenTemp = resultField.getText();
        calResult = Double.parseDouble(screenTemp);
        if(calResult!= 0)  calResult = Math.pow(calResult, tempNum);
        resultField.setText(Double.toString(calResult));
    }//GEN-LAST:event_btnXActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        
        screenTemp = resultField.getText();
        calResult = Double.parseDouble(screenTemp);
        if(calResult!=0) {
            calResult = Math.log(calResult);
            resultField.setText(Double.toString(calResult));
        }
    }//GEN-LAST:event_btnInActionPerformed

    private void Sta42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta42ActionPerformed

    private void btnDmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDmsActionPerformed

    private void btnFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFEActionPerformed

    private void Sta45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta45ActionPerformed

    private void Sta46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta46ActionPerformed

    private void btnFactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactoActionPerformed
        
        screenTemp = resultField.getText();
        calResult = Integer.parseInt(screenTemp);
        int startNum = 1;

        try {
        while(calResult > 1) {
            startNum *= calResult;
            calResult--;
        }
        resultField.setText(Integer.toString((int) startNum));
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "정수 값의 팩토리얼 계산만 가능합니다", "계산 불가", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btnFactoActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        calResult = Double.parseDouble(screenTemp);
        if(calResult!=0){
            calResult = Math.tan(Math.toRadians(calResult));
            resultField.setText(Double.toString(calResult));
        }
    }//GEN-LAST:event_btnTanActionPerformed

    private void btn1xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1xActionPerformed
        
        tempNum = Double.valueOf(screenTemp);
        
        // * 연산기호를 두 번 누르는 걸 방지할 코드 필요 
        
        // 결과가 초기값(0)이면 계산한 적이 없는 것,
        // 결과에 스크린에 있는 값을 실수로 형변환한 tempNum 입력
        if(tempNum != 0){
            calResult = 1/tempNum;
            // 문자로 변환 후 화면에 출력
            strResult = String.valueOf(calResult);
            resultField.setText(strResult);   
        } else {
            JOptionPane.showMessageDialog(null, "분모에는 0이 올 수 없습니다.", "계산 불가", JOptionPane.ERROR_MESSAGE); 
            
        }
            tempNum = 0; // 현재숫자 초기화
            screenTemp = "";
    }//GEN-LAST:event_btn1xActionPerformed

    private void btnX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2ActionPerformed
        
        screenTemp = resultField.getText();
        calResult = Double.parseDouble(screenTemp);
        if(calResult!= 0)  calResult = Math.pow(calResult, 2);
        resultField.setText(Double.toString(calResult));
    }//GEN-LAST:event_btnX2ActionPerformed

    private void btnMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMPActionPerformed
        
        tempNum = Double.valueOf(screenTemp);
        calResult = tempNum + Double.valueOf(strMemory);
        
        strResult = String.valueOf(calResult);
        screenTemp = strResult;
        resultField.setText(strResult);
    }//GEN-LAST:event_btnMPActionPerformed

    private void btnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiActionPerformed
        
        calResult = Math.PI;
        resultField.setText(Double.toString(calResult));
    }//GEN-LAST:event_btnPiActionPerformed

    private void btnMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMSActionPerformed
        strMemory = screenTemp;
        resultField.setText(strMemory);
    }//GEN-LAST:event_btnMSActionPerformed

    private void btnMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCActionPerformed
        strMemory = "";
        resultField.setText(strMemory);
    }//GEN-LAST:event_btnMCActionPerformed

    private void btnMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRActionPerformed
        resultField.setText(strMemory);
        screenTemp = strMemory;
    }//GEN-LAST:event_btnMRActionPerformed

    private void Sta56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta56ActionPerformed

    private void Sta57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta57ActionPerformed

    private void Sta58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta58ActionPerformed

    private void Sta59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta59ActionPerformed

    private void btnIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntActionPerformed
        screenTemp = resultField.getText();
        calResult = Double.parseDouble(screenTemp);
        if(calResult!=0){
            int temp = (int)calResult;
            resultField.setText(Integer.toString(temp));
        }  
    }//GEN-LAST:event_btnIntActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        // 계산 결과 도출
        tempNum = Double.valueOf(strResult);
        
        switch (strOperator) {
            case "+" -> calResult += tempNum;
            case "-" -> calResult -= tempNum;
            case "*" -> calResult *= tempNum;
            case "/" -> calResult /= tempNum;
            case "%" -> calResult %= tempNum;
            case "^" -> calResult = (int)tempNum ^ (int)calResult;
            case "&" -> calResult = (int)tempNum & (int)calResult;
            case "|" -> calResult = (int)tempNum | (int)calResult;
            case "<" -> calResult = (int)tempNum << (int)calResult;
            default -> {
            }
        }
        
        strResult = String.valueOf(calResult);
        
        resultField.setText(strResult);
        strOperator = "";
    }//GEN-LAST:event_btnResultActionPerformed

    private void resultFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultFieldActionPerformed

    private void rbtnDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDecActionPerformed
        
        strResult = resultField.getText();
        tempNum = Double.parseDouble(strResult);
        
        if(tempNum!=0){
            strResult = String.valueOf(tempNum);
            resultField.setText(strResult);
        }
    }//GEN-LAST:event_rbtnDecActionPerformed

    private void rbtnHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnHexActionPerformed
        
        strResult = resultField.getText();
        tempNum = Double.parseDouble(strResult);
        
        if(tempNum!=0){
            String strHex = Double.toHexString(tempNum);
            resultField.setText(strHex);
        }
    }//GEN-LAST:event_rbtnHexActionPerformed

    private void rbtnOctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOctActionPerformed
        
        strResult = resultField.getText();
        tempNum = Double.parseDouble(strResult);
        
        if(tempNum!=0){
            String strOct = Integer.toOctalString((int) tempNum);
            resultField.setText(strResult);
        } 
    }//GEN-LAST:event_rbtnOctActionPerformed

    private void rbtnBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnBinActionPerformed
        
        strResult = resultField.getText();
        tempNum = Double.parseDouble(strResult);
        
        if(tempNum!=0){
            String strBin = Integer.toBinaryString((int)tempNum);
            resultField.setText(strResult);
        }
    }//GEN-LAST:event_rbtnBinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOne;
    private javax.swing.JButton BtnThree;
    private javax.swing.JButton BtnTwo;
    private javax.swing.JButton Sta30;
    private javax.swing.JButton Sta31;
    private javax.swing.JButton Sta32;
    private javax.swing.JButton Sta42;
    private javax.swing.JButton Sta45;
    private javax.swing.JButton Sta46;
    private javax.swing.JButton Sta56;
    private javax.swing.JButton Sta57;
    private javax.swing.JButton Sta58;
    private javax.swing.JButton Sta59;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn1x;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAnd;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnComma;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDms;
    private javax.swing.JButton btnFE;
    private javax.swing.JButton btnFacto;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnInt;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnLsh;
    private javax.swing.JButton btnMC;
    private javax.swing.JButton btnMP;
    private javax.swing.JButton btnMR;
    private javax.swing.JButton btnMS;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnNot;
    private javax.swing.JButton btnOr;
    private javax.swing.JButton btnPM;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSta;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnX2;
    private javax.swing.JButton btnX3;
    private javax.swing.JButton btnXor;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton rbtnBin;
    private javax.swing.JRadioButton rbtnDec;
    private javax.swing.JRadioButton rbtnHex;
    private javax.swing.JRadioButton rbtnOct;
    private javax.swing.JTextField resultField;
    // End of variables declaration//GEN-END:variables
}
